window=Tk()
window.title('Tkinter Sample Window')
window.geometry('300x300')
greeting=Label(text="HELLO USER",fg='black',bg='white')
button=Button(text="HERE",bg='black',fg='white')
entry=Entry(fg='blue',bg='green',width=40)
greeting.pack()
button.pack()
entry.pack()
frame=Frame(master=window,relief=RAISED,borderwidth=5)
frame.pack()
label=Label(master=frame,text='SAMPLE FRAME')
label.pack()
textbox=Text(fg='green',bg='blue')
textbox.pack()
window.mainloop()